### ISSUE TITLE
Allow JSON to be passed as a String to SchemaMapper (add sourceType support in #221)

### ISSUE THREAD

**Issue by diegosoaresub** [joelittlejohn/jsonschema2pojo#255] opened 2014-10-03 13:13 UTC
Hello,

In http://www.jsonschema2pojo.org/ I could convert JSON to POJO, but using the API this not work, only Json Schema to POJO. Is possible do this with the API?

In this case below, I didn't get exception but It doesn't generate the java file.

JCodeModel codeModel = new JCodeModel();
SchemaMapper schemaMapper = new SchemaMapper();
schemaMapper.generate(codeModel, className, packageName, "{\"titulo\": \"JSON\"}");
codeModel.build(new File("output"));

**Comment by sanalsan** [comment] 2015-11-27 10:43
Hello,
Is there any hope for this bug ?

**Comment by joelittlejohn** [comment] 2015-11-27 10:45
@sanalsan happy to accept a pull request for this if you are interested in fixing it.

**Comment by sanalsan** [comment] 2015-11-27 11:30
Hello Joe,

can you please tell me the error in it ?

package com.schoolspeak.modelgenerator;

import android.os.Bundle;
import android.os.Environment;
import android.support.v7.app.AppCompatActivity;

import com.sun.codemodel.JCodeModel;

import org.jsonschema2pojo.DefaultGenerationConfig;
import org.jsonschema2pojo.GenerationConfig;
import org.jsonschema2pojo.Jackson2Annotator;
import org.jsonschema2pojo.SchemaGenerator;
import org.jsonschema2pojo.SchemaMapper;
import org.jsonschema2pojo.SchemaStore;
import org.jsonschema2pojo.SourceType;
import org.jsonschema2pojo.rules.RuleFactory;

import java.io.File;
import java.io.IOException;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        generateClassFromJsonString();
    }
    private File getFile(){
        File mPath = new
File(Environment.getExternalStorageDirectory(), "Model");
        if (!mPath.exists()) {
            try {
                mPath.mkdir();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        return mPath;
    }
    private void generateClassFromJsonString(){
        JCodeModel codeModel = new JCodeModel();
        String jsonString="{ \"accounting\" : [   \n" +
                "                                { \"firstName\" :
\"John\",  \n" +
                "                                  \"lastName\"  : \"Doe\",\n" +
                "                                  \"age\"       : 23 },\n" +
                "\n" +
                "                                { \"firstName\" :
\"Mary\",  \n" +
                "                                  \"lastName\"  :
\"Smith\",\n" +
                "                                  \"age\"       : 32 }\n" +
                "                              ],
      \n" +
                "              \"sales\"       : [ \n" +
                "                                { \"firstName\" :
\"Sally\", \n" +
                "                                  \"lastName\"  :
\"Green\",\n" +
                "                                  \"age\"       : 27 },\n" +
                "\n" +
                "                                { \"firstName\" :
\"Jim\",   \n" +
                "                                  \"lastName\"  :
\"Galley\",\n" +
                "                                  \"age\"       : 41 }\n" +
                "                              ] \n" +
                "            } ";


        final GenerationConfig config = new DefaultGenerationConfig() {
            @Override
            public SourceType getSourceType() {
                return SourceType.JSON;
            }
        };
        SchemaMapper mapper = new SchemaMapper(new RuleFactory(config,
new Jackson2Annotator(),
                new SchemaStore()), new SchemaGenerator());
        try {
            mapper.generate(codeModel,"sample", "com.sample.model.",
                    jsonString);
        } catch (IOException e) {
            e.printStackTrace();
        }

        try {
            codeModel.build(getFile());
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

}


On Fri, Nov 27, 2015 at 4:15 PM, Joe Littlejohn <notifications@github.com>
wrote:

> @sanalsan <https://github.com/sanalsan> happy to accept a pull request
> for this if you are interested in fixing it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joelittlejohn/jsonschema2pojo/issues/255#issuecomment-160110964>
> .
>



-- 
Thanks & Regards,
Sanal K | Software Developer
Suyati Technologies | http://www.suyati.com
*skalathingal@suyati.com <hcherian@socxo.com>*| P: 9895442668
[image: http://www.suyati.com/images/signature_new/white.jpg][image:
LinkedIn]
<http://t.strk03.email/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsQZbjKW7dSn5C1px3lzW7fsH1M56dBH6f80fbP402?t=https%3A%2F%2Fin.linkedin.com%2Fpub%2Fsanal-k%2F6a%2F782%2F216&si=5828738894266368&pi=24522bb9-f3f7-467f-c171-7f46f9199641>[image:
http://www.suyati.com/images/signature_new/white.jpg][image: Facebook]
<http://t.strk03.email/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsQZbjKW7dSn5C1px3lzW7fsH1M56dBH6f80fbP402?t=https%3A%2F%2Fwww.facebook.com%2Fsanal.saw&si=5828738894266368&pi=24522bb9-f3f7-467f-c171-7f46f9199641>[image:
http://www.suyati.com/images/signature_new/white.jpg][image: Twitter]
<http://t.strk03.email/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsQZbjKW7dSn5C1px3lzW7fsH1M56dBH6f80fbP402?t=https%3A%2F%2Ftwitter.com%2Fsanal_san&si=5828738894266368&pi=24522bb9-f3f7-467f-c171-7f46f9199641>

**Comment by joelittlejohn** [comment] 2015-11-27 11:47
The error is exactly as described already:

> the change made in #221 to allow source documents to be generated from strings doesn't use the config correctly, so it doesn't support sourceType=JSON. You'll need to use a URL to pass the JSON content.

**Comment by sanalsan** [comment] 2015-12-08 05:01
Thank you Joe :)

On Fri, Nov 27, 2015 at 5:17 PM, Joe Littlejohn <notifications@github.com>
wrote:

> The error is exactly as described already:
>
> the change made in #221
> <https://github.com/joelittlejohn/jsonschema2pojo/pull/221> to allow
> source documents to be generated from strings doesn't use the config
> correctly, so it doesn't support sourceType=JSON. You'll need to use a URL
> to pass the JSON content.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joelittlejohn/jsonschema2pojo/issues/255#issuecomment-160122238>
> .
>



-- 
Thanks & Regards,
Sanal K | Software Developer
Suyati Technologies | http://www.suyati.com
*skalathingal@suyati.com <hcherian@socxo.com>*| P: 9895442668
[image: http://www.suyati.com/images/signature_new/white.jpg][image:
LinkedIn]
<http://t.strk03.email/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsQZbjKW7dSn5C1px3lzW7fsH1M56dBH6f80fbP402?t=https%3A%2F%2Fin.linkedin.com%2Fpub%2Fsanal-k%2F6a%2F782%2F216&si=5828738894266368&pi=24522bb9-f3f7-467f-c171-7f46f9199641>[image:
http://www.suyati.com/images/signature_new/white.jpg][image: Facebook]
<http://t.strk03.email/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsQZbjKW7dSn5C1px3lzW7fsH1M56dBH6f80fbP402?t=https%3A%2F%2Fwww.facebook.com%2Fsanal.saw&si=5828738894266368&pi=24522bb9-f3f7-467f-c171-7f46f9199641>[image:
http://www.suyati.com/images/signature_new/white.jpg][image: Twitter]
<http://t.strk03.email/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsQZbjKW7dSn5C1px3lzW7fsH1M56dBH6f80fbP402?t=https%3A%2F%2Ftwitter.com%2Fsanal_san&si=5828738894266368&pi=24522bb9-f3f7-467f-c171-7f46f9199641>

**Comment by joelittlejohn** [comment] 2016-01-06 16:54
Closed by #475

**Closed by joelittlejohn** 2016-01-06 16:54 UTC
Labels: enhancement

**Comment by JohnLuCN** [comment] 2018-04-02 09:45
I encountered the same exception, and finally found that the error is caused by field name which is using Chinese Characters....After changing to PinYin or English characters, exception will be eliminated.
Hope there could be some upgrade for such kind of situation:))
