### ISSUE TITLE
`equals()` code generation uses incorrect comparison methods.

### ISSUE THREAD

**Issue by Woodham** [joelittlejohn/jsonschema2pojo#1214] opened 2021-03-15 15:20 UTC
~The generated `equals()` method currently uses `==` for `String` fields. This will compare object equality for the fields rather than value equlity - is this intended?~ - ignore this, on closer inspection I can see it's using `==` as a pre-test before `.equals()`

It also uses `.equals()` for `BigDecimal` fields (e.g. when `useBigDecimals` is true). This is a problem because `equals()` on `BigDecimal` will only result in `true` if both the value _and_ scale are equal (e.g. `2.00` will not equal `2.0`). It usually makes more sense to compare `BigDecimal` using `.compareTo()` which can compare mathematical equality.

**Comment by joelittlejohn** [comment] 2021-03-15 17:59
Hi Chris. I guess we need to introduce a special case here for BigDecimal as it does seem that using compareTo would be more useful. Is this a random observation btw or did you hit a problem with this?

**Comment by Woodham** [comment] 2021-03-15 19:10
I was actually just testing this for the first time and in the project I also use [Spotbugs](https://spotbugs.github.io/) with [fb-contrib](http://fb-contrib.sourceforge.net) additions to scan for bugs, and it highlighted both the above issues when I generated the code (though obviously the first one was a false positive :) ).

The specific error code for the big decimal issue was `MDM_BIGDECIMAL_EQUALS`

**Comment by HectorBst** [comment] 2021-03-15 22:59
Hi,

Interesting problem!

This is not a bug in jsonschema2pojo, this issue is rather caused by the implementation of BigDecimal, which was designed like this (there may be a reason for this choice). Adding a functionality to handle this tricky behavior directly in jsonschema2pojo is a good idea, but I think it should be optional, via the configuration, to not force the new behavior. And in my opinion, it should currently be disabled by default, otherwise it could constitute a breaking change.

If we change the behavior of equals, we also need to do it for hashCode, or we will break the equals / hashCode consistency (hashCode uses value and scale too).

A possible alternative to compareTo is the stripTrailingZeros method, made precisely to normalize a BigDecimal, but it induces the creation of a temporary new instance for each comparison.

**Comment by joelittlejohn** [comment] 2021-03-16 08:43
@HectorBst I think you're right that it might be overstepping to decide that everyone wants this 'logical' equals comparison. Particularly as it deviates from the current behaviour.

I'm inclined to close this with no action for now.

**Comment by HectorBst** [comment] 2021-03-16 18:02
An optional feature that can be enabled through configuration could still be very useful for those wanting to use the BigDecimal's numerical equality instead of the default behavior (this use case shouldn't be uncommon).

**Comment by joelittlejohn** [comment] 2021-03-21 21:33
Yes, I can see it could be useful. However we have a huge number of configuration options to maintain. Since this has been found only through automated scanning and we don't intend to change the default, most people wont ever find or need this config option and there is no actual demand.

**Closed by joelittlejohn** 2021-03-21 21:33 UTC
