### ISSUE TITLE
Get Stackoverflow error if schema contains trees/cycle dependencies for children

### ISSUE THREAD

**Issue by etsybaev** [joelittlejohn/jsonschema2pojo#875] opened 2018-06-08 15:27 UTC
Get Stackoverflow error if schema contains trees/cycle dependencies for children.

**Steps:**
1. open web site http://www.jsonschema2pojo.org/
2. insert this schema to web site:
{  
   "type":"array",
   "items":{  
      "$ref":"#/definitions/node"
   },
   "definitions":{
      **"node":**{  
         "type":"object",
         "properties":{
           **"childList":{  
               "type":"array",
               "items":{  
                  "$ref":"#/definitions/node"**
               }
            }
         }
      }
   },
   "$schema":"http://json-schema.org/draft-04/schema#"
} 

3. Click on generate

**Actual Result:**
There's a problem:
HTTP ERROR: 500
Problem accessing /generator/preview. Reason:
java.lang.StackOverflowError

**Expected result:**
Generated class that looks like:

import java.util.List;
public class **Node** {
    List<**Node**> childList;
    //getters and setters here
}

**Comment by krasilnikovdmtr** [comment] 2018-06-08 18:46
Actually, there's a similar example in the [documentation](https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference).

    {
       "description" : "Tree node",
       "type" : "object",
       "properties" : {
          "children" : {
             "type" : "array",
             "items" : {
                 "$ref" : "#"
             }
          }
       }
    }

According to the documentation, it should produce the following java code

     public class TreeNode {
    
       public List<TreeNode> getChildren() {...}
    
       public void setChildren(List<TreeNode> children) {...}
    
    }

In fact, it throws StackOverflowError. You can test this json schema here - http://www.jsonschema2pojo.org/

**Comment by joelittlejohn** [comment] 2018-06-14 16:47
Resolving this as a duplicate of #781

**Closed by joelittlejohn** 2018-06-14 16:47 UTC

**Comment by etsybaev** [comment] 2018-06-15 14:40
The issue is still reproducible if you pass json as a String
