### ISSUE TITLE
Hidden files such as .DS_Store are not ignored

### ISSUE THREAD

**Issue by paulalewis** [joelittlejohn/jsonschema2pojo#359] opened 2015-05-18 18:47 UTC
When I run the generator if there is a .DS_Store file in the json schema directory the build will fail. Wondering if this is by design or if this is a bug.

**Comment by joelittlejohn** [comment] 2015-05-18 19:46
I'm surprised no one has mentioned this before, it's possible that a fix in the most recent version has caused this. Having said that, I don't think that we have been ignoring .* before.

@ctrimble will probably have a good opinion on this.

**Comment by ctrimble** [comment] 2015-05-18 21:05
@paulalewis what interface are you using (CLI, Maven, Gradle, etc)?  This is one of the things that I was having trouble with and the Maven plugin should be ignoring `.DS_Store` by default.  I would assume that  the other interfaces would fail on any non JSON file, hidden or not.  If this behavior has changed, I would be happy to get the problem corrected.

**Comment by paulalewis** [comment] 2015-05-18 21:26
@ctrimble We are using it with Gradle in our Android Studio project and it is not ignoring .DS_Store by default. It does seem to fail as you say on any non json file.

**Comment by ctrimble** [comment] 2015-05-18 21:35
Well, I never built out the functionality for Gradle, since I wasn't sure what the convention for file filters was in Gradle.  Ultimately, the generator just needs to be supplied a java.io.FileFilter.  The current default implementation just accepts all files.

**Comment by ctrimble** [comment] 2015-05-18 21:41
Assuming that we should support [FileTrees](https://gradle.org/docs/current/userguide/working_with_files.html#sec:file_trees) in Gradle for this.

**Comment by ctrimble** [comment] 2015-05-18 23:00
@joelittlejohn in #332, you mentioned that excluding files like '.*' might be a good idea.  That could probably be implemented as the default behavior for now, without too much trouble.  File and directory names starting with `.` probably do not generate working code anyway.  Thoughts?

**Comment by zambro** [comment] 2015-05-27 17:45
I also ran into the same problem using Maven. Deleting the file fixed the problem for now. Would be great to have this ignored by default.

**Comment by ctrimble** [comment] 2015-05-27 19:12
@zambro I would not expect you to see this problem with more recent versions of the Maven plugin.  What version are you running?

**Comment by zambro** [comment] 2015-05-27 19:46
@ctrimble I am running 3.1.1

**Comment by ctrimble** [comment] 2015-05-27 20:01
@zambro sorry, I was talking about the version of jsonschema2pojo.

**Comment by zambro** [comment] 2015-05-27 20:06
0.4.11

**Comment by ctrimble** [comment] 2015-05-27 20:17
@zambro I just fixed some issues with file filtering for 0.4.12-SNAPSHOT.  Your issue should be resolved in the next release.  I am using Maven's default excludes for this, which can be found in the [shared utilities](http://grepcode.com/file/repo1.maven.org/maven2/org.apache.maven.shared/maven-shared-utils/0.6/org/apache/maven/shared/utils/io/DirectoryScanner.java?av=f#118).

**Comment by joelittlejohn** [comment] 2015-05-27 20:19
Thanks @ctrimble. I'll cut a release soon.

**Comment by joelittlejohn** [comment] 2015-05-28 19:52
I'm going to close this as it's fixed in 0.4.12. Feel free to reopen after that release if you're still having trouble.

**Closed by joelittlejohn** 2015-05-28 19:52 UTC

**Comment by ctrimble** [comment] 2015-06-01 16:28
@joelittlejohn this should not be an issue for Maven, but `.DS_Store` files will still be a problem for all other interfaces in `0.4.12` if no action is taken.

**Comment by samskiter** [comment] 2015-08-06 10:55
Looks like this has regressed with v0.4.14. 0.4.12&0.4.13 have the class loader issue so I'm a bit stuck at the minute.

**Comment by samskiter** [comment] 2015-08-06 10:57
@joelittlejohn @crrimble looks like this has regressed with v0.4.14. I also have the classloader issue with the NoopAnnotator, so I'm a bit stuck with no versions currently working for me :(

**Comment by ctrimble** [comment] 2015-08-06 17:12
@samskiter I am sorry to hear that you are having an issue with this.  I will take a look today and see if I can identify the source of the issue.

**Comment by samskiter** [comment] 2015-08-06 17:14
Hey, thanks for getting back to me. If I manage the files carefully I can
avoid the ds_store being created now. I'm using gradle builds, btw.

**Comment by ctrimble** [comment] 2015-08-06 17:23
@samskiter Oh, this is a Maven only feature right now, since it wasn't clear to me how to do this in a way that is natural to Gradle.  I could probably get this support on all interfaces, but just for standard files like `.DS_Store` and directories like `.svn`.

**Comment by ctrimble** [comment] 2015-08-06 18:44
The Gradle [Copy Task](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/groovy/org/gradle/api/tasks/Copy.java) seems to support file filtering just like Maven.  Perhaps a fix could be patterned on it.

**Comment by joelittlejohn** [comment] 2015-08-06 21:18
Hi @samskiter. I'm a little confused by the timeline here, but maybe I misunderstood your earlier comment.

So it sounds like we don't have a regression, rather the Gradle plugin has never ignored these files. So are .DS_Store files something that weren't present in your directories when you were using the plugin previously?

One issue we have here is that we only have a small number of contributors who are familiar with Gradle. @samskiter it would be great if you could take a look at the [CopyTask](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/groovy/org/gradle/api/tasks/Copy.java)/[AbstractCopyTask](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/groovy/org/gradle/api/tasks/AbstractCopyTask.java) and consider creating a PR that will apply some [default excludes similar to Maven](https://github.com/apache/maven-shared/blob/d65d60a4bbe78d7e901bab119455f8a2858e7fb3/maven-shared-utils/src/main/java/org/apache/maven/shared/utils/io/DirectoryScanner.java#L118).

**Comment by samskiter** [comment] 2015-08-09 09:27
@joelittlejohn I hadn't quite realised this did not apply to the gradle plugin, so there is no regression here - just a new bug.

I will have a look over the copytask stuff and see if I can work out what to do :)
