### ISSUE TITLE
Valid JSON Schema throws StackOverflowException

### ISSUE THREAD

**Issue by giordanolucas** [joelittlejohn/jsonschema2pojo#826] opened 2018-01-22 19:26 UTC
Having the following schema:
`{
  "$ref": "#/definitions/BatchRetrieveCatalogObjectsResponse",
  "definitions": {
    "Error": {
      "type": "object",
      "properties": {
        "category": {
          "type": "string"
        },
        "code": {
          "type": "string"
        },
        "detail": {
          "type": "string"
        },
        "field": {
          "type": "string"
        }
      }
    },
    "CatalogV1Id": {
      "type": "object",
      "properties": {
        "catalog_v1_id": {
          "type": "string"
        },
        "location_id": {
          "type": "string"
        }
      }
    },
    "CatalogModifierOverride": {
      "type": "object",
      "properties": {
        "modifier_id": {
          "type": "string"
        },
        "on_by_default": {
          "type": "boolean"
        }
      }
    },
    "CatalogItemModifierListInfo": {
      "type": "object",
      "properties": {
        "modifier_list_id": {
          "type": "string"
        },
        "modifier_overrides": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CatalogModifierOverride"
          }
        },
        "min_selected_modifiers": {
          "type": "integer"
        },
        "max_selected_modifiers": {
          "type": "integer"
        },
        "enabled": {
          "type": "boolean"
        }
      }
    },
    "ItemVariationLocationOverrides": {
      "type": "object",
      "properties": {
        "location_id": {
          "type": "string"
        },
        "price_money": {
          "type": "object",
          "properties": {
            "amount": {
              "type": "integer"
            },
            "currency": {
              "type": "string"
            }
          }
        },
        "pricing_type": {
          "type": "string"
        },
        "track_inventory": {
          "type": "boolean"
        },
        "inventory_alert_type": {
          "type": "string"
        },
        "inventory_alert_threshold": {
          "type": "integer"
        }
      }
    },
    "CatalogObject": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "updated_at": {
          "type": "string"
        },
        "version": {
          "type": "integer"
        },
        "is_deleted": {
          "type": "boolean"
        },
        "catalog_v1_ids": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CatalogV1Id"
          }
        },
        "present_at_all_locations": {
          "type": "boolean"
        },
        "present_at_location_ids": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "absent_at_location_ids": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "item_data": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "abbreviation": {
              "type": "string"
            },
            "label_color": {
              "type": "string"
            },
            "available_online": {
              "type": "boolean"
            },
            "available_for_pickup": {
              "type": "boolean"
            },
            "available_electronically": {
              "type": "boolean"
            },
            "category_id": {
              "type": "string"
            },
            "tax_ids": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "modifier_list_info": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/CatalogItemModifierListInfo"
              }
            },
            "image_url": {
              "type": "string"
            },
            "variations": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/CatalogObject"
              }
            },
            "product_type": {
              "type": "string"
            },
            "skip_modifier_screen": {
              "type": "boolean"
            }
          }
        },
        "category_data": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            }
          }
        },
        "item_variation_data": {
          "type": "object",
          "properties": {
            "item_id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "sku": {
              "type": "string"
            },
            "upc": {
              "type": "string"
            },
            "ordinal": {
              "type": "integer"
            },
            "pricing_type": {
              "type": "string"
            },
            "price_money": {
              "type": "object",
              "properties": {
                "amount": {
                  "type": "integer"
                },
                "currency": {
                  "type": "string"
                }
              }
            },
            "location_overrides": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ItemVariationLocationOverrides"
              }
            },
            "track_inventory": {
              "type": "boolean"
            },
            "inventory_alert_type": {
              "type": "string"
            },
            "inventory_alert_threshold": {
              "type": "integer"
            },
            "user_data": {
              "type": "string"
            },
            "service_duration": {
              "type": "integer"
            }
          }
        },
        "tax_data": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "calculation_phase": {
              "type": "string"
            },
            "inclusion_type": {
              "type": "string"
            },
            "percentage": {
              "type": "string"
            },
            "applies_to_custom_amounts": {
              "type": "boolean"
            },
            "enabled": {
              "type": "boolean"
            }
          }
        },
        "discount_data": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "discount_type": {
              "type": "string"
            },
            "percentage": {
              "type": "string"
            },
            "amount_money": {
              "type": "object",
              "properties": {
                "amount": {
                  "type": "integer"
                },
                "currency": {
                  "type": "string"
                }
              }
            },
            "pin_required": {
              "type": "boolean"
            },
            "label_color": {
              "type": "string"
            }
          }
        },
        "modifier_list_data": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "selection_type": {
              "type": "string"
            },
            "modifiers": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/CatalogObject"
              }
            }
          }
        },
        "modifier_data": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "price_money": {
              "type": "object",
              "properties": {
                "amount": {
                  "type": "integer"
                },
                "currency": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "BatchRetrieveCatalogObjectsResponse": {
      "type": "object",
      "properties": {
        "errors": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Error"
          }
        },
        "objects": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CatalogObject"
          }
        },
        "related_objects": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CatalogObject"
          }
        }
      }
    }
  },
  "$schema": "http://json-schema.org/draft-04/schema#"
}`

It throws an StackOverflowException when I try to generate a POJO from it

![image](https://user-images.githubusercontent.com/27356984/35240062-0b6bd584-ff91-11e7-91d4-04f948669669.png)

**Comment by joelittlejohn** [comment] 2018-06-14 16:48
Resolving this as a duplicate of #781

**Closed by joelittlejohn** 2018-06-14 16:48 UTC
