### ISSUE TITLE
$ref to enum creates inner class instead of using the other class

### ISSUE THREAD

**Issue by M-Wong** [joelittlejohn/jsonschema2pojo#437] opened 2015-10-30 08:43 UTC
Let's say I have the following two schemas:
Base.json

``` json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "type": "object",

    "properties": {
        "type": { "type": "object", "$ref": "./MyEnum.json" }
    }
}
```

MyEnum.json

``` json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "description": "DocumentSafe.DocumentStateType",
    "type": "object",
    "enum": ["ONE", "TWO"]
}
```

With this I would expect the generated classes to be like:

``` java
public class Base {
    private MyEnum type;
}

public enum MyEnum {
    ONE("ONE"), TWO("TWO");
}
```

What I get however is the following:

``` java
public class Base {
    private Base.Type type;

    public static enum Type {
        ONE("ONE"), TWO("TWO");
    }
}

public enum MyEnum {
    ONE("ONE"), TWO("TWO");
}
```

**Comment by kumartheashwani** [comment] 2016-01-02 17:40
@ctrimble Can I work on this issue.

**Comment by ctrimble** [comment] 2016-01-02 19:01
I am not aware of anyone working on this, so give it a go.  This is [the line](https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/SchemaRule.java#L71) you are interested in.  Make sure that the tool can still generate the old style of enums.  This is what I would do:

1. Review the current integration tests and make sure they cover both top level and nested enums.  Add any tests that seem to be missing.
2. Add a new flag to change the enum style.
3. Add integration tests with the new flag activated.

**Comment by ctrimble** [comment] 2016-01-02 19:12
@kumartheashwani I am not aware of anyone working on this.  This is [the line](https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/SchemaRule.java#L71) you are interested in.  Something will need to be done to ensure that existing nested enums still work, since that could result in breaking currently generated code.

**Comment by kumartheashwani** [comment] 2016-01-04 01:22
Thanks @ctrimble let me analyze and come up with a plan on how to support both the formats.

**Comment by joelittlejohn** [comment] 2016-01-04 10:58
The problem here is the order in which the schemas are read. It's somewhat related to #164. This is unfortunately a side-effect of the fundamental way in which this project handles `$ref` links and is not something that is easily fixed.

If MyEnum.json is read first, you would get a standalone type generated, and this would then be used when Base is generated. In your case, Base.json is read first, and this then reads MyEnum.json as a subordinate to Base when it resolves this $ref.

You don't state how you are using jsonschema2pojo (Maven plugin?). One workaround you could use here is to keep your enums in a separate directory and ensure these are read first (e.g. use sourcePaths with the enum directory first in the list, or invoke the plugin multiple times during your build).

**Comment by dadrus** [comment] 2016-01-12 14:53
could you please check whether the solution referenced by #481 solves this problem as well?

**Comment by kicsikrumpli** [comment] 2016-06-23 09:17
As a practical duct tape I added leading underscores to the "$ref"-ed json's file name to manually order the processing of the json files. Not a nice fix, but a good enough workaround. This also solves the issue of declaring an "extends" in the schema, and instead of properly naming the generated base class, it has the name of the descendant class with "Base" tacked to the end. (e.g.: Foo extends Bar generates Foo.class and FooBase.class)

**Comment by andrewmellinger** [comment] 2016-09-08 15:18
Is this bug still under active work?

**Comment by DamageShadow** [comment] 2016-11-29 21:01
Can anybody take a look on this issue? It still exists in the latest version ...

**Comment by s13o** [comment] 2017-03-15 21:06
The simple workaround is to spesify a java class name at  [javaType](https://github.com/joelittlejohn/jsonschema2pojo/wiki/Reference#extensions) property in definition of Enum

**Comment by pnewhook** [comment] 2017-11-16 22:30
I'm also running into this. Though in my case it builds fine on my Mac locally, but fails on a Jenkins build server (RHEL). I'm using the maven plugin with JDK 6. The order should be fine, my enum is in Constants.json and my consuming classes are RemoveSessionRq.json. I'm on version 0.4.37

Constants.json
```
{
	"$schema": "http://json-schema.org/schema#",
	"id": "http://www.company.com/service/schemas/json/Constants.json",
	"title" : "ConstantsTypes",
	"description" : "Definition of constant types",
	"type": "object",
	"definitions": {
		"sessionType" : {
			"type" : "string",
			"enum" : ["USER", "WSOD"]
		}
	}, 
	"properties" : {
		"sessionType" : {
			"type" : "object",
			"required" : "true",
			"$ref" : "#/definitions/sessionType"
		}
	}
}
``` 

RemoveSessionRq.json
```
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "id": "http://www.company.com/service/schemas/json/RemoveSessionRq.json",
    "title" : "RemoveSessionRq",
    "description" : "RemoveSession REST json schema",
    "type": "object",
    "extends" : { "$ref" : "BaseRestRequest.json" },
    "properties" : {
		"sessionType" : {
			"type" : "object",
			"required" : "true",
			"$ref" : "Constants.json#/definitions/sessionType"
		},
		"sessionData" : {
			"type" : "object",
			"required" : "true",
			"$ref" : "WMSessionManagerTypes.json#/definitions/sessionData"
		}
    }
}
```

**Comment by hydra1983** [comment] 2018-01-15 07:39
@s13o The generated file is a ```class```, not a ```enum```

```java
public class FuncFlag {

    ZT_001("ZT001"),
    ZT_002("ZT002"),
    VT_003("VT003");
    private final String value;
    private final static Map<String, FuncFlag> CONSTANTS = new HashMap<String, FuncFlag>();

    static {
        for (FuncFlag c: values()) {
            CONSTANTS.put(c.value, c);
        }
    }

    private FuncFlag(String value) {
        this.value = value;
    }

    @Override
    public String toString() {
        return this.value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static FuncFlag fromValue(String value) {
        FuncFlag constant = CONSTANTS.get(value);
        if (constant == null) {
            throw new IllegalArgumentException(value);
        } else {
            return constant;
        }
    }

}
```

**Comment by joelittlejohn** [comment] 2018-01-31 21:22
Closing as a duplicate of #164

**Closed by joelittlejohn** 2018-01-31 21:22 UTC
Labels: bug
