### ISSUE TITLE
Regression wont generate class

### ISSUE THREAD

**Issue by robertsearle** [joelittlejohn/jsonschema2pojo#1446] opened 2022-11-09 01:48 UTC
Regression This wont work since there is a json field `common` with a common field name in both sample json files. 
1.1.1 works fine
1.1.2 doesn't work

  [bad-json.tgz](https://github.com/joelittlejohn/jsonschema2pojo/files/9966536/bad-json.tgz)

```
  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.jsonschema2pojo</groupId>
          <artifactId>jsonschema2pojo-maven-plugin</artifactId>
          <version>${jsonschema2pojo-maven-plugin.version}</version>
          <configuration>
            <annotationStyle>jackson2</annotationStyle>
            <dateTimeType>java.time.ZonedDateTime</dateTimeType>
            <dateType>java.time.LocalDate</dateType>
            <formatDateTimes>true</formatDateTimes>
            <includeAdditionalProperties>false</includeAdditionalProperties>
            <includeConstructors>true</includeConstructors>
            <includeGeneratedAnnotation>true</includeGeneratedAnnotation>
            <includeToString>true</includeToString>
            <removeOldOutput>true</removeOldOutput>
            <sourceType>json</sourceType>
            <sourceDirectory>${basedir}/src/main/json-samples/</sourceDirectory>
            <sourceSortOrder>FILES_FIRST</sourceSortOrder>
            <targetLanguage>java</targetLanguage>
            <targetVersion>${java.version}</targetVersion>
            <useCommonsLang3>true</useCommonsLang3>
          </configuration>
          <dependencies>
            <dependency>
              <groupId>org.jsonschema2pojo</groupId>
              <artifactId>jsonschema2pojo-maven-plugin</artifactId>
              <version>${jsonschema2pojo-maven-plugin.version}</version>
            </dependency>
          </dependencies>
          <executions>
            <execution>
              <goals>
                <goal>generate</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
      </plugins>
```

**Comment by unkish** [comment] 2022-12-21 13:43
Looks like a duplicate of https://github.com/joelittlejohn/jsonschema2pojo/issues/1427

**Closed** 2023-01-07 12:03 UTC
