### ISSUE TITLE
LocalMaven didn't work at current master(HEAD)

### ISSUE THREAD

**Issue by simpleton** [joelittlejohn/jsonschema2pojo#363] opened 2015-05-28 10:07 UTC
error info 
```
Error:Unable to load class 'org.jsonschema2pojo.NoopAnnotator'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
```

It works at 6caf3ca which is the first commit after tag 0.4.11

**Comment by ben-manes** [comment] 2015-05-28 10:14
Sounds like the integration test failed for some unknown reason. It passes locally, so you may want to wipe out your `~/.gradle/caches/` folder. You can use `mvn install -DskipTests` instead.

**Comment by joelittlejohn** [comment] 2015-06-13 21:47
I'm tentatively going to close this as fixed by the latest changes. If you're still having problems please let us know.

**Closed by joelittlejohn** 2015-06-13 21:47 UTC

**Comment by jsuksl** [comment] 2015-08-04 08:14
you can reproduce this issue by setting 'customAnnotator = 'org.jsonschema2pojo.NoopAnnotator' in your jsonschema2pojo-gradle-plugin/example/android/app/build.gradle

```
* What went wrong:
A problem occurred evaluating project ':app'.
> org.jsonschema2pojo.NoopAnnotator

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':app'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:54)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:148)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:59)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:504)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:83)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:47)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:129)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
Caused by: java.lang.ClassNotFoundException: org.jsonschema2pojo.NoopAnnotator
	at java_lang_Class$forName$0.call(Unknown Source)
	at org.jsonschema2pojo.gradle.JsonSchemaExtension.setCustomAnnotator(JsonSchemaExtension.groovy:114)
	at org.jsonschema2pojo.gradle.JsonSchemaExtension_Decorated.setCustomAnnotator(Unknown Source)
	at org.gradle.api.internal.BeanDynamicObject$MetaClassAdapter.setProperty(BeanDynamicObject.java:187)
	at org.gradle.api.internal.BeanDynamicObject.setProperty(BeanDynamicObject.java:112)
	at org.gradle.api.internal.CompositeDynamicObject.setProperty(CompositeDynamicObject.java:101)
	at org.jsonschema2pojo.gradle.JsonSchemaExtension_Decorated.setProperty(Unknown Source)
	at build_d5afhh7wecqv3sdmyyzmz0eew$_run_closure3.doCall(/Users/jsuk/Documents/github/jsonschema2pojo/jsonschema2pojo-gradle-plugin/example/android/app/build.gradle:92)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:63)
	at org.gradle.api.internal.plugins.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:145)
	at org.gradle.api.internal.plugins.ExtensionsStorage.configureExtension(ExtensionsStorage.java:69)
	at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.invokeMethod(DefaultConvention.java:207)
	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:147)
	at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
	at build_d5afhh7wecqv3sdmyyzmz0eew.run(/Users/jsuk/Documents/github/jsonschema2pojo/jsonschema2pojo-gradle-plugin/example/android/app/build.gradle:41)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
	... 35 more
```

**Comment by ben-manes** [comment] 2015-08-04 08:22
I think this is because the classloader of the caller is Groovy, not the script. Most likely using `Thread.currentThread().getContextClassLoader().loadClass("...")` will work to bind to the plugin's classloader.
