### ISSUE TITLE
How can I disable path evaluation?

### ISSUE THREAD

**Issue by yeikel** [joelittlejohn/jsonschema2pojo#1434] opened 2022-09-17 22:00 UTC
Starting with 1.1.2, I am seeing the following error: 

`Execution default of goal org.jsonschema2pojo:jsonschema2pojo-maven-plugin:1.1.2:generate failed: Path not present: $%7BRFC_NUMBER%7D`

Example: 

```json
"variables": {
    "${RFC_NUMBER}": "",
}
```

In this case, the variable `${RFC_NUMBER}"` is a literal and there is no need to evaluate it

Configuration

```xml

<plugin>
                <groupId>org.jsonschema2pojo</groupId>
                <artifactId>jsonschema2pojo-maven-plugin</artifactId>
                <version>1.1.2</version>
                <configuration>
                    <sourceDirectory>${basedir}/src/main/resources/schema/</sourceDirectory>
                    <targetPackage>com.models</targetPackage>
                    <sourceType>json</sourceType>
                    <annotationStyle>gson</annotationStyle>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

```

The same code works as is in 1.1.1

**Comment by joelittlejohn** [comment] 2023-01-07 12:03
This is a duplicate of #1402.

**Closed by joelittlejohn** 2023-01-07 12:03 UTC
