### ISSUE TITLE
Publish gradle plugin properly

### ISSUE THREAD

**Issue by yelhouti** [joelittlejohn/jsonschema2pojo#1408] opened 2022-05-31 07:40 UTC
This is to restate what was mentioned here:
https://github.com/joelittlejohn/jsonschema2pojo/issues/1106

When looking for gradle plugins google automatically sends you here: https://plugins.gradle.org/search?term=jsonschema2pojo

But you plugin is not present.

Others have tried publishing it but under different names and not always with the latest version.

It would be great if on each release the plugin was updated automatically.

Also this would allow using the plugin by adding only one line to the plugins block:
 ```yaml
plugins {
    ...
    id "org.jsonschema2pojo" version "x.y.z"
}
 ```

**Comment by joelittlejohn** [comment] 2022-08-06 12:39
Duplicate of #282.

**Closed by joelittlejohn** 2022-08-06 12:39 UTC
