### ISSUE TITLE
NameHelper java.lang.StringIndexOutOfBoundsException: String index out of range: 0

### ISSUE THREAD

**Issue by mpitoniak** [joelittlejohn/jsonschema2pojo#851] opened 2018-04-07 21:57 UTC
greetings,

NameHelper.capitalizeTrailingWords(String name) 

 while parsing some ansible json response code i get an StringIndexOutOfBoundsException.
problem is last line in json response below:  "_": "/usr/bin/python"
capitalizeTrailingWords has to guard for edge case of strings less than 2 chars...

cheers,

mp

"ansible_env": {
                                    "HOME": "/home/admin", 
                                    "LANG": "en_US.UTF-8", 
                                    "LESSOPEN": "||/usr/bin/lesspipe.sh %s", 
                                    "LOGNAME": "admin", 
                                    "LS_COLORS": "", 
                                    "MAIL": "/var/mail/admin", 
                                    "PATH": "/usr/local/bin:/usr/bin:/opt/jdk1.8.0_161/bin:/opt/jdk1.8.0_161/jre/bin:/opt/jdk1.8.0_161/bin:/opt/jdk1.8.0_161/jre/bin", 
                                    "PWD": "/home/admin", 
                                    "SELINUX_LEVEL_REQUESTED": "", 
                                    "SELINUX_ROLE_REQUESTED": "", 
                                    "SELINUX_USE_CURRENT_RANGE": "", 
                                    "SHELL": "/bin/bash", 
                                    "SHLVL": "2", 
                                    "SSH_CLIENT": "10.0.4.100 54746 22", 
                                    "SSH_CONNECTION": "10.0.4.100 54746 10.7.3.221 22", 
                                    "SSH_TTY": "/dev/pts/0", 
                                    "USER": "admin", 
                                    "XDG_RUNTIME_DIR": "/run/user/1000", 
                                    "XDG_SESSION_ID": "47098", 
                                    "_": "/usr/bin/python"
                                }

**Comment by mpitoniak** [comment] 2018-04-07 21:59
...should have said great product...thx for developing this very nice util!
mp

**Comment by thachhoang** [comment] 2018-04-27 22:05
This is a duplicate of #632, you should check out the proposed fixes there. For now though, you need at least one valid character in the name.

**Closed by thachhoang** 2018-04-27 22:05 UTC
