### ISSUE TITLE
generate-api , needs to report the path to the field for failure.

### ISSUE THREAD

**Issue by chabhishek123** [joelittlejohn/jsonschema2pojo#607] opened 2016-08-12 19:30 UTC
I am trying to create pojo from schema. I am noticing the error . It will help if which field ( line number, file ) where the error is observed. The error is : 
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution generate-api of goal org.jsonschema2pojo:jsonschema2pojo-maven-plugin:0.4.24:generate failed: trying to create the same field twice: additionalProperties
	at org

I have checked through script if the same field is present twice, it is not present. Please help me fix this.

COMPLETE STACK TRACE:

[ERROR] Failed to execute goal org.jsonschema2pojo:jsonschema2pojo-maven-plugin:0.4.24:generate (generate-api) on project xyz-spec: Execution generate-api of goal org.jsonschema2pojo:jsonschema2pojo-maven-plugin:0.4.24:generate failed: trying to create the same field twice: additionalProperties -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jsonschema2pojo:jsonschema2pojo-maven-plugin:0.4.24:generate (generate-api) on project xyz-spec: Execution generate-api of goal org.jsonschema2pojo:jsonschema2pojo-maven-plugin:0.4.24:generate failed: trying to create the same field twice: additionalProperties
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution generate-api of goal org.jsonschema2pojo:jsonschema2pojo-maven-plugin:0.4.24:generate failed: trying to create the same field twice: additionalProperties
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: java.lang.IllegalArgumentException: trying to create the same field twice: additionalProperties
	at com.sun.codemodel.JDefinedClass.field(JDefinedClass.java:425)
	at com.sun.codemodel.JDefinedClass.field(JDefinedClass.java:396)
	at org.jsonschema2pojo.rules.AdditionalPropertiesRule.addAdditionalPropertiesField(AdditionalPropertiesRule.java:128)
	at org.jsonschema2pojo.rules.AdditionalPropertiesRule.apply(AdditionalPropertiesRule.java:108)
	at org.jsonschema2pojo.rules.AdditionalPropertiesRule.apply(AdditionalPropertiesRule.java:43)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:135)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:70)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:90)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:40)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:73)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:66)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:75)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:43)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:64)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:32)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:125)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:70)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:90)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:40)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:73)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:66)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30)
	at org.jsonschema2pojo.rules.ArrayRule.apply(ArrayRule.java:81)
	at org.jsonschema2pojo.rules.ArrayRule.apply(ArrayRule.java:37)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:113)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:40)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:73)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:75)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:43)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:64)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:32)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:125)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:70)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:90)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:40)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:73)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:66)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30)
	at org.jsonschema2pojo.rules.ArrayRule.apply(ArrayRule.java:81)
	at org.jsonschema2pojo.rules.ArrayRule.apply(ArrayRule.java:37)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:113)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:40)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:73)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:75)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:43)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:64)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:32)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:125)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:70)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:90)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:40)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:73)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:66)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30)
	at org.jsonschema2pojo.SchemaMapper.generate(SchemaMapper.java:92)
	at org.jsonschema2pojo.Jsonschema2Pojo.generate(Jsonschema2Pojo.java:75)
	at org.jsonschema2pojo.maven.Jsonschema2PojoMojo.execute(Jsonschema2PojoMojo.java:594)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	... 20 more

**Comment by ctrimble** [comment] 2016-08-12 20:10
@chabhishek123 this can happen if your schema has a property named `additionalProperties` and it also has `"additionalProperties": true` set.

**Comment by chabhishek123** [comment] 2016-08-12 21:59
@ctrimble : Thanks for the suggestion, i have checked the whole repo for multiple additionalProperties field, but it is not present. Either ways if the path to the field, file is added to the error log , it will be helpful.

**Comment by joelittlejohn** [comment] 2016-08-13 00:39
@chabhishek123 could you provide an example that produces the error? I'd recommend trying to narrow this down by simplifying your schema, delete done parts. Could you also provide the config options you are using for the Maven plugin?

**Comment by ctrimble** [comment] 2016-08-13 07:41
#608 contains a test case that produces the same exception as the cause here.

**Comment by joelittlejohn** [comment] 2016-09-24 09:32
Closing this as we don't have enough info. It's likely that @ctrimble has diagnosed this correctly. Another possibility is passing a JSON schema as input but setting sourceType to JSON (this is a common way of accidentally including a field named additionalProperties that you didn't expect). Since you mention that you don't have additionalProperties defined as a field anywhere, maybe the latter problem is what's happening here.

**Closed by joelittlejohn** 2016-09-24 09:32 UTC
