### ISSUE TITLE
com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class modals.MMiscellaneous$Miscellaneous]: can not instantiate from JSON 

### ISSUE THREAD

**Issue by TheGreat0004** [joelittlejohn/jsonschema2pojo#537] opened 2016-03-22 12:09 UTC
May be this is an earlier opened issue but i had tried my every effort to make it workable but failed,

I had posted a question on stackoverflow, whose link is as follow,

http://stackoverflow.com/questions/36152061/jackson-jsonmappingexception-cannot-instantinate?noredirect=1#comment59944689_36152061

**Comment by joelittlejohn** [comment] 2016-03-22 23:24
So it looks like your problem was caused by mixing code from two different generators. Can this one be closed now?

**Comment by TheGreat0004** [comment] 2016-03-23 03:59
no, but i would like to know only this time it didn't worked but every time it works with other enclosed innter classed without declaring them as static an i am not using any extra tool for generating pojo classes.

**Comment by joelittlejohn** [comment] 2016-03-23 11:20
What I don't understand is why you have inner classes. This system only uses inner classes for enums, and you don't have any enums.

I think you have introduced a problem when copying the code from jsonschema2pojo.org

**Comment by joelittlejohn** [comment] 2016-03-28 19:28
Closing this one as I believe it's caused by an error copying the code out of the page. If you can still reproduce this, please provide some more information.

**Closed by joelittlejohn** 2016-03-28 19:28 UTC
