### ISSUE TITLE
String index out of range: 0 error while generating pojo from json

### ISSUE THREAD

**Issue by Vibhu123** [joelittlejohn/jsonschema2pojo#838] opened 2018-03-06 21:13 UTC
I am working on one of the sample json files to generate the corresponding pojos. However I am getting String index out of range:0 error. Can someone please debug it and see where the issue might be. I think it might be with one of the properties used like "#" or "$". Attaching the file for your reference.
[Airtypesv6.json.zip](https://github.com/joelittlejohn/jsonschema2pojo/files/1786741/Airtypesv6.json.zip)

**Comment by joelittlejohn** [comment] 2018-03-07 15:53
Closing this as a duplicate of #632. We need at least one valid character in there at the moment, but we should fix this.

With the solution I proposed in https://github.com/joelittlejohn/jsonschema2pojo/issues/632#issuecomment-254922182, you would see `__number_sign` for "#" and `__dollar_sign` for "$".

**Closed by joelittlejohn** 2018-03-07 15:53 UTC
