### ISSUE TITLE
Java class names should be consistent

### ISSUE THREAD

**Issue by Kiemes** [joelittlejohn/jsonschema2pojo#836] opened 2018-03-02 15:51 UTC
When you have two schemas where one object references the other, the resulting classes depend on how the files are named. This is ok in general, but it should be consistent. 

Example:
`b.json`
```
{
    "type": "object",
    "properties": {
        "reference": {
            "$ref": "c.json"
        }
    }
}
```

`c.json`
```
{
    "type": "object",
    "properties": {
        "value": {
            "type": "string"
        }
    }
}
```

I am using the maven plugin (version 0.5.1) to generate Java classes out of this.
As the tool goes through all files sorted by the filename, `b.json` is parsed first. As `c.json` was not yet parsed, the corresponding Java class `B` will contain a field with name `reference` and type `Reference`. You end up with two classes `B` and `Reference`.

If you now rename `c.json` to `a.json`, the file `a.json` will be parsed first and create a class `A`. Then schema `b.json` will be parsed and create a class `B` which contains a field with name `reference` and type `A`. You end up with two classes `A` and `B`.

I would expect it to always be the names of the schema files. So in example 1, I would expect `B` and `C`.

**Comment by Kiemes** [comment] 2018-03-02 16:47
It might be handled [here](https://github.com/joelittlejohn/jsonschema2pojo/blob/24e1ab86799aa2c13317c03e01f0b4d7cdae6b39/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/SchemaRule.java#L67)?

**Comment by joelittlejohn** [comment] 2018-03-03 19:59
Hi Tom. This is actually one of the major differences in 1.0.0. I have changed the way that makes are chosen when you use a ref.

Could you try 1.0.0-alpha1 and let me know how you get on?

**Comment by Kiemes** [comment] 2018-03-05 09:55
@joelittlejohn thanks for the hint. I was reluctant to use a version which is marked as alpha and unstable ;)

Anyhow, 1.0.0-alpha1 produces what I expected.

When looking at the diff of the generated classes (compared to 0.5.1), I saw that you removed `commons-lang` dependency and implement `toString`, `hashCode` and `equals` method yourself. Any reason for that?

Also, I wonder why `jackson-databind` is not a dependency in [jsonschema2pojo-maven-plugin/pom.xml](https://github.com/joelittlejohn/jsonschema2pojo/blob/24e1ab86799aa2c13317c03e01f0b4d7cdae6b39/jsonschema2pojo-maven-plugin/pom.xml#L37-L55)

Besides the `toString`, `hashCode` and `equals` methods, there were no changes in the generated classes. So I am going to use 1.0.0-alpha for now.

**Comment by joelittlejohn** [comment] 2018-03-05 10:51
One of the changes in 1.0.0-alpha1 is #812. It removes a dependency on commons-lang (which many people have wanted to do) and should produce a faster implementation. There are some breaking changes in the 1.0 release (and more planned) including the way classes are named when using `$ref`, so this is spending a small period in alpha to ensure that we get some early testing whilst things can still change.

jackson-databind is not a direct dependency of jsonschema2pojo-maven-plugin. jsonschema2pojo-core has a dependency of jackson-databind, and this core is used by the maven plugin, the cli, the gradle task, the ant task, etc. So jackson-databind is a transitive dependcy, but not a direct dependency, of jsonschema2pojo-maven-plugin.

I'm going to close this one as a duplicate of #164.

Cheers!

**Closed by joelittlejohn** 2018-03-05 10:51 UTC
