### ISSUE TITLE
Generator uses first property name to create java class names instead of json type name

### ISSUE THREAD

**Issue by samuel-kerrien** [joelittlejohn/jsonschema2pojo#481] opened 2016-01-06 12:47 UTC
We have discovered that when defining reusable schema element it appears that the java class generated is named after the first field that uses this type.

To illustrate my point, here is a sample schema (file: example.json):

``` json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "sex": {
      "$ref": "#/definitions/shared_class"
    },
    "job": {
      "$ref": "#/definitions/shared_class"
    }
  },
  "definitions": {
    "shared_class": {
      "type": "object",
      "properties": {
        "uri": {
          "type": "string"
        }
      }
    }
  }
}
```

note that the 'shared_class' definition is used twice in the schema.
The resulting generated class are as follow:

``` java
@JsonInclude(JsonInclude.Include.NON_NULL)
@Generated("org.jsonschema2pojo")
@JsonPropertyOrder({
    "uri"
})
public class Sex {

    @JsonProperty("uri")
    private String uri;
    protected final static Object NOT_FOUND_VALUE = new Object();

    ...
}
```

``` java
@JsonInclude(JsonInclude.Include.NON_NULL)
@Generated("org.jsonschema2pojo")
@JsonPropertyOrder({
    "sex",
    "job"
})
public class Example {

    @JsonProperty("sex")
    private Sex sex;

    @JsonProperty("job")
    private Sex job;
    protected final static Object NOT_FOUND_VALUE = new Object();

...
}
```

Note that if in the schema, the property 'job' had come first, the generated class would have been Job and not Sex.

I suppose the correct behaviour would be in the case where there is a $ref to use the name of the type rather than the property name. In this case the generated class would be 'SharedClass'.

Obviously, I can add use the 'javaType' property as follow to force that class to be generated but this also forces me to put java code reference into my schema that it doesn't feel right.

``` json
...
"shared_class": {
      "type": "object",
      "javaType": "com.company.example.SharedClass",
      "properties": {
        "uri": {
          "type": "string"
        }
      }
    }
...
```

**Comment by dadrus** [comment] 2016-01-08 15:11
Same issue applies while referencing external schema files. Here a slightly modified example from above, which introduces an `address_definition` element and externalizes the `job` definition. 
```.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "address_definition": { "$ref": "address.jsonschema" },
    "sex": { "$ref": "#/definitions/shared_class" },
    "job_description": { "$ref": "job.jsonschema" }
  },
  "definitions": {
    "shared_class": {
      "type": "object",
      "properties": {
        "uri": { "type": "string" }
      }
    }
  }
}
```

The `job.jsonschema` may look like
```.json
{
    "$schema": "http://json-schema.org/schema#",
    "description": "A Job definition",
    "type": "object",
    "properties": {
    	"title": { "type": "string" }
    },
    "required": ["title"]
}
```
And the `address.jasonschema` may look like 

```.json
{
    "$schema": "http://json-schema.org/schema#",
    "description": "An Address definition",
    "type": "object",
    "properties": {
        "street_address": { "type": "string" },
        "city": { "type": "string" },
        "state": { "type": "string" }
    },
    "required": ["stree_address", "city", "state"]
}
```
Depending on the name of the external schema file the current implementation will name the type either based on the property name or based on the file name:
* if the external schema is loaded and processed before it is referenced, the name of the type is derived from the file name
* in all other cases the name of the type is derived from the name of the first encountered property, which reference that type.

That mens:
* in case of `address_definition` the resulting generated class will be named `Address`, not `AddressDefinition` (see below)
* in case of `job_description` the resulting generated class will be named `JobDescription` and not `Job`, which would be consistent with the behavior for the top level schema file (and which is actually desired). 

The commit referenced above fixes both issues (internally referenced types and externally referenced types). I've "tested" it in a debugger by generating the corresponding class from the above definitions. Unfortunately I have not figured out (yet), how to implement corresponding Unit/Integration -Tests for this project. Maybe someone can support me here, so that the fix can be reviewed (and enhanced, integrated into the main stream) by the project members.

**Comment by dadrus** [comment] 2016-01-12 14:43
The last commit (see above) is a further enhancement of this issue. Now, not only classes are handled like described above, the generation of enums based on the above rules is supported as well.

Previosly all enums where named based on the name of the first property (or based on the file name, see comments above) making use of the corresponding definition, regardless (except mentioned file name cases) whether the enum is an anonymous definition, defined in the same schema file as its own type, or was defined in an other schema file. The above commit breaks this rule. It implements the following rules for enums

- If the enum is defined as an anonymous type, like
```.json
{
    "type": "object",
    "properties": {
         "my_enum": {  "enum": ["black", "white"]  }
    }
}
```` 
the generated enum class is named `MyEnum` and is contained within the class, generated for the given schema definition. The corresponding `myEnum` property of the class is of that type.

- If the enum is defined as an own type in the same file, like
```.json
{
    "definitions": {
        "enum_type": {
             "enum": ["black", "white"]
        }
    },
    "type": "object",
    "properties": {
         "my_enum": {  "$ref": "#/definitions/enum_type"  }
    }
}
```` 
the generated enum class is named `EnumType` and is contained within the package, generated for the given schema definition. The corresponding `myEnum` property of the class is of that type.

- If the enum is defined as an own type in another file, the rule 2 applies as well with the difference, that the package name depends on the schema file defining that enum.

In addition to this this commit provides support for JSON schema ids. The implemented rules are as follows:

- if the id is not present, everything defined by that schema file is generated into the *"default"* package.

- If the id is present and no mapping is provided, everything belonging to that id is generated into a package which name is derived from the id. JAX-B rules apply here.

- If the id is present and a mapping is provided, everything belonging to that id is generated into a package which name is defined by the mapping.

Like before, the *"default"* package can be defined using the `targetPackage` configuration option. E.g.
```.xml
<plugin>
    <groupId>org.jsonschema2pojo</groupId>
    <artifactId>jsonschema2pojo-maven-plugin</artifactId>
    <version>0.4.19-SNAPSHOT</version>
    <configuration>
        <sourceDirectory>${basedir}/src/main/resources/schema</sourceDirectory>
	<targetPackage>com.example.types</targetPackage>
    </configuration>
</plugin>
```

The id mapping is configurable as well and can be done using the new introduced `idMappings` configuration options. E.g.
```.xml
<plugin>
    <groupId>org.jsonschema2pojo</groupId>
    <artifactId>jsonschema2pojo-maven-plugin</artifactId>
    <version>0.4.19-SNAPSHOT</version>
    <configuration>
        <sourceDirectory>${basedir}/src/main/resources/schema</sourceDirectory>
	<targetPackage>com.example.types</targetPackage>
        <idMappings>
             <idMapping>
                 <id>http://some-super-duper-uri.com/2016/01/my_definition</id>
                 <packageName>com.test</packageName>
             </idMapping>
        </idMappings>
    </configuration>
</plugin>
```
Given this configuration the corresponding types for the `http://some-super-duper-uri.com/2016/01/my_definition` will be generated into the `com.test` package. Without the mapping the package name is derived from the id, based on the JAX-B rules. That is the above `id` will be mapped to `com.some_super_duper_uri/_2016/_01/my_definition` package.

The id is optional and if given defines the namespace for all elements defined within the corresponding schema. E.g.
```.json
{
    "id": "http://some-super-duper-uri.com/2016/01/my_definition"
    "definitions": {
        "enum_type": {
             "enum": ["black", "white"]
        }
    },

    "type": "object",
    "properties": {
         "my_enum": {  "$ref": "#/definitions/enum_type"  }
    }
}
```` 
In the above example the top level type, as well as the `enum_type` from the `definitions` element belong to the schema with `id` *"http://some-super-duper-uri.com/2016/01/my_definition"*. Thus will both be generated into the corresponding package. If however the `enum_type` would define its own `id`, this `id` would define the namespace, thus the corresponding java package.

Corresponding tests were added and old affected tests were adjusted. I hope the community will give it a try. At least this is a starting point.

**NOTE:** Be aware, this breaks, how the types were generated in the past.

**Comment by dadrus** [comment] 2016-01-12 14:57
I forgot to mention, that only the Maven plugin was enhanced with the possibility to map ids to package names. All other plugins lack this possibility right now. That means, with these plugins the id is transfered to appropriate java package names based on JAX-B rules.

**Comment by samskiter** [comment] 2016-05-23 20:51
related, alternative proposal: https://github.com/joelittlejohn/jsonschema2pojo/issues/554

**Comment by kiaSso** [comment] 2016-06-04 15:02
Hi guys, i downloaded the version 0.4.23 and i see this fix is not there.
Am I being blind or it hasn't been released yet?

Thanks

**Comment by dredwolff** [comment] 2017-07-06 19:31
We are running into this issue, as well as a problem where the things defined in the "definitions" section are not getting generated as classes at all if they're being referenced as a oneOf, allOf or anyOf field. :(

**Comment by joelittlejohn** [comment] 2018-01-31 21:20
Duplicate of #164

**Closed by joelittlejohn** 2018-01-31 21:20 UTC
