### ISSUE TITLE
build failed with 0.4.20

### ISSUE THREAD

**Issue by maksimlikharev** [joelittlejohn/jsonschema2pojo#509] opened 2016-02-22 17:16 UTC
:xxxxx:generateJsonSchema2Pojo FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':xxx:generateJsonSchema2Pojo'.
> java.lang.NullPointerException (no error message)

rolling back to version 0.4.18

Will provide more info afer I fix all my broken projects as of now

**Comment by maksimlikharev** [comment] 2016-02-22 17:25
Caused by: java.lang.NullPointerException
	at org.jsonschema2pojo.Jsonschema2Pojo.getAnnotator(Jsonschema2Pojo.java:141)
	at org.jsonschema2pojo.Jsonschema2Pojo.generate(Jsonschema2Pojo.java:55)
	at org.jsonschema2pojo.Jsonschema2Pojo$generate.call(Unknown Source)
	at org.jsonschema2pojo.gradle.GenerateJsonSchemaJavaTask.generate(GenerateJsonSchemaJavaTask.groovy:65)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)

**Comment by joelittlejohn** [comment] 2016-02-22 17:29
Thanks @maksimlikharev. Would you be able to post your configuration?

**Comment by joelittlejohn** [comment] 2016-02-22 17:30
Also, I'm interested to know if 0.4.19 also fails for you.

**Comment by maksimlikharev** [comment] 2016-02-22 17:32
0.4.19 works file, there is a different problem, but on our end, configuration what is used:
jsonSchema2Pojo {
  includeJsr303Annotations = false
  includeHashcodeAndEquals = false
  includeToString = false
  usePrimitives = true
  generateBuilders = true
  source = files("${sourceSets.main.output.resourcesDir}/schema")
  targetDirectory = file("src/generated-sources")
  propertyWordDelimiters = ['_'] as char[]
}

**Comment by joelittlejohn** [comment] 2016-02-22 17:36
Sounds like this is caused by changes made for #495

**Comment by joelittlejohn** [comment] 2016-02-22 17:47
@ramib85 it looks like the 'java' task may not be working in some scenarios after your changes. Can you see anything obvious that would cause this?

**Comment by maksimlikharev** [comment] 2016-02-22 17:55
the only additional info I have
1. java plugin applied in the root projects:
  subprojects {
    apply plugin: 'java'
   ...
}

and we still on a gradle 2.2

**Comment by ramib85** [comment] 2016-02-22 20:47
Hi, 
you are right, my previous pull request has introduced this issue.
The jsonSchema2Pojo configuration is null when the plugin calls GenerateJsonSchemaJavaTask.generate

I have fixed it in a new pull request 
https://github.com/joelittlejohn/jsonschema2pojo/pull/510

**Comment by joelittlejohn** [comment] 2016-02-23 10:05
This should be fixed by the changes I have just merged from #510. 

@maksimlikharev I have released 0.4.21-beta-1 which should appear in Maven central in the next few hours.

**Comment by joelittlejohn** [comment] 2016-02-23 10:07
Also, if you're a Gradle user please consider helping us improve the testing of the Gradle plugin. I don't use Gradle and didn't create the plugin. It's clear that we could do with having some better end-to-end tests for this (even a simple smoke test would have found this problem). This would be a very welcome contribution.

**Closed** 2016-02-23 10:07 UTC

**Comment by joelittlejohn** [comment] 2016-02-23 19:13
@maksimlikharev 0.4.21-beta-1 is out now. Could you give this a test and let me know if your problem is fixed?

**Comment by maksimlikharev** [comment] 2016-02-23 20:24
0.4.21-beta-1 - works for me, thank you

**Comment by ben-manes** [comment] 2016-03-02 07:58
@joelittlejohn 

Its not quite clear what a test for the plugin means. Is it configuration settings, Java/Android compilation, or the generated code? `ProjectBuilder` is a mocking approach that works for basic scenarios. The newer `Gradle TestKit` invokes a full build in a controlled manner, and might be more useful. As this was written prior to the TestKit, the `Gradle Connector` is used for a [smoke test](https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-gradle-plugin/src/test/groovy/org/jsonschema2pojo/gradle/JsonSchemaPluginSpec.groovy#L27) that runs the Java example to detect a failed build. The simplest might be to add more cases for the smoke test, as the example project is quite simple.

**Comment by joelittlejohn** [comment] 2016-03-02 10:08
@ben-manes yes, we have the same problem with the maven plugin. Full end-to-end tests tend to be really slow for Maven plugins, so we hook in a bit deeper and invoke the plugin 'as if' it were invoked by Maven. There's definitely scope for a code change to break the way that the Maven plugin works by causing failure when Maven injects its configuration. This kind of change is rare though, and the benefit we get from testing without Maven is really fast tests that are also _much_ simpler to write (and understand when the fail).

Do you think there's a simple way to ensure an issue like this one (Gradle plugin works for Android projects but is broken for plain Java projects) could not happen without the build failing?

**Comment by ben-manes** [comment] 2016-03-02 10:17
I think the approach your describing for Maven is like Gradle's `ProjectBuilder` which is also very fast. Since the plugin doesn't have a lot of logic, though, I'm not sure how valuable that is compared to a smoke test. It seems your maven plugin similarly has few tests, since there's not much needed, so a few more smoke tests is probably all you want.

I think this break was for multi-project builds, right? The example is a single-project build, which if broke should have failed your build. If my understanding is correct, then you could add a multi-project smoke test too. Due to Android requiring an installed SDK, to add that smoke test would require some [travis configuration](https://docs.travis-ci.com/user/languages/android) magic.
